### ISSUE TITLE
Auto-instrument Symfony Console events

### ISSUE THREAD

**Issue by gaelreyrol** [FriendsOfOpenTelemetry/opentelemetry-bundle#1]
Console events should be auto-instrumented through an EventSubscriber.

Documentation: https://symfony.com/doc/current/components/console/events.html

## Configuration

```yaml
open_telemetry:
  instrumentation:
    console:
      enabled: true
      tracing:
         enabled: true
         tracer: ~
      metering:
        enabled: true
        meter: ~
```

When `open_telemetry.instrumentation.console.enabled` is set to false, a compiler pass should remove the tag `kernel.event_subscriber` from the EventSubscriber.

The value of `open_telemetry.instrumentation.console.tracing.tracer` should target the default trace provider if not defined or not overwritten, if set it should match a provider defined in `open_telemetry.traces.tracers`.

The value of `open_telemetry.instrumentation.console.metering.meter` should target the default meter provider if not defined or not overwritten, if set it should match a provider defined in `open_telemetry.metrics.meters`.

### `ConsoleEvents::COMMAND`
1. Create a span with the command name
2. Defines attributes (Code function & namespace)
3. Store span in current context

### `ConsoleEvents::ERROR`
1. Get current span
2. Set span status to error
3. Record exception in span with exit code

### `ConsoleEvents::TERMINATE`
1. Get scope from context
2. Detach scope
3. Get span from context scope
4. Add exit code as span attribute
5. Set span status based on exit code
6. End span

### `ConsoleEvents::SIGNAL`
1. Get current span
2. Add handled signal as span attribute
