### ISSUE TITLE
Allow to exclude some console command by configuration

### ISSUE THREAD

**Issue by Kaspiman** [FriendsOfOpenTelemetry/opentelemetry-bundle#128]
For example, i don't want to trace infra-commands like: `cache:clear` or `assets:install` (https://symfony.com/doc/current/console.html).

So, we will have config like this:

```
open_telemetry:
  instrumentation:
    console:
      exclude:
        - ^cache:clear$
        - ^assets:install$
```

Also, similar feature already here https://github.com/FriendsOfOpenTelemetry/opentelemetry-bundle/issues/126

Could i do this thing?
