### ISSUE TITLE
 Auto-instrument Symfony Messenger events

### ISSUE THREAD

**Issue by gaelreyrol** [FriendsOfOpenTelemetry/opentelemetry-bundle#13]
Messenger events should be auto-instrumented through an EventListener.

Documentation: https://symfony.com/doc/current/messenger.html#messenger-events

## Configuration

```yaml
open_telemetry:
  instrumentation:
    messenger:
      enabled: true
      tracing:
         enabled: true
         tracer: ~
      metering:
        enabled: true
        meter: ~
```

When `open_telemetry.instrumentation.messenger.enabled` is set to false, a compiler pass should remove the tag `kernel.event_listener` from the EventListener.

The value of `open_telemetry.instrumentation.messenger.tracing.tracer` should target the default trace provider if not defined or not overwritten, if set it should match a provider defined in `open_telemetry.tracing.tracers`.

The value of `open_telemetry.instrumentation.messenger.metering.meter` should target the default meter provider if not defined or not overwritten, if set it should match a provider defined in `open_telemetry.metrics.meters`.

### `WorkerStoppedEvent`
