### ISSUE TITLE
Messenger component not working

### ISSUE THREAD

**Issue by ShaklinDmitry** [FriendsOfOpenTelemetry/opentelemetry-bundle#132]
why tracing may not work in a component Messenger
Components Http Client and Cache  work great and I see it in the jaeger. But the messenger component for some reason doesn't work. 
Could you tell me where the problem might be?

this config file
```
# Default configuration for extension with alias: "open_telemetry"
open_telemetry:
  service:
    namespace:           MyOrganization
    name:                name
    version:             1.0.0
    environment:         '%kernel.environment%'
  instrumentation:

    http_kernel:
      type: auto # One of "auto"; "attribute"
      tracing:
        enabled: true

        # The tracer to use, defaults to `traces.default_tracer` or first tracer in `traces.tracers`
        tracer: 'open_telemetry.traces.tracers.main'


    messenger:
      type: auto # One of "auto"; "attribute"
      tracing:
        enabled: true

        # The tracer to use, defaults to `traces.default_tracer` or first tracer in `traces.tracers`
        tracer: 'open_telemetry.traces.tracers.main'


  traces:
    tracers:
      main:
        # A tracer must refer a provider using the service id pattern `open_telemetry.traces.providers.<provider_name>`.
        provider: 'open_telemetry.traces.providers.default'
    providers:
      default:
        type: default
        sampler: always_on
        processors:
          # A provider must refer one or more processor using the service id pattern `open_telemetry.traces.processors.<processor_name>`.
          - 'open_telemetry.traces.processors.simple'
    processors:
      simple:
        type: simple
        # A processor must refer an exporter using the service id pattern `open_telemetry.traces.exporters.<exporter_name>`.
        exporter: 'open_telemetry.traces.exporters.otlp'
    exporters:
      otlp:
        dsn: http+otlp://jaeger:4318/v1/traces
```

and default messenger call like this
`  $this->messageBus->dispatch(new TestCommand('name', 'description'));
`
