### ISSUE TITLE
Auto-instrument Symfony Mailer events

### ISSUE THREAD

**Issue by gaelreyrol** [FriendsOfOpenTelemetry/opentelemetry-bundle#14]
Messenger events should be auto-instrumented through an EventListener.

Documentation: https://symfony.com/doc/current/mailer.html#mailer-events

## Configuration

```yaml
open_telemetry:
  instrumentation:
    mailer:
      enabled: true
      tracing:
         enabled: true
         tracer: ~
      metering:
        enabled: true
        meter: ~
```

When `open_telemetry.instrumentation.mailer.enabled` is set to false, a compiler pass should remove the tag `kernel.event_listener` from the EventListener.

The value of `open_telemetry.instrumentation.mailer.tracing.tracer` should target the default tracer provider if not defined or not overwritten, if set it should match a tracer defined in `open_telemetry.tracing.tracers`.

The value of `open_telemetry.instrumentation.mailer.metering.meter` should target the default meter provider if not defined or not overwritten, if set it should match a tracer defined in `open_telemetry.metrics.meters`.

### `FailedMessageEvent`
