### ISSUE TITLE
Document how to exclude commands from being traced

### ISSUE THREAD

**Issue by gaelreyrol** [FriendsOfOpenTelemetry/opentelemetry-bundle#149]
Commands can be excluded from being traced when instrumentation is set to auto:

```yaml
open_telemetry:
  instrumentation:
    console:
      type: auto
      tracing:
        enabled: true
        exclude_commands:
          - ^assets:install$
```
