### ISSUE TITLE
HttpKernel Instrumentation - Empty exclude_paths excludes all paths

### ISSUE THREAD

**Issue by jvocampings** [FriendsOfOpenTelemetry/opentelemetry-bundle#162]
Hello

here a basic conf of HttpKernel instrumentation to reproduce:

```
instrumentation:
    http_kernel:
        type: auto
        tracing:
            enabled: true
            tracer: 'open_telemetry.traces.tracers.main'
            exclude_paths: []
```

All paths will be excluded by `TraceableHttpKernelEventSubscriber::isAutoTraceable()` https://github.com/FriendsOfOpenTelemetry/opentelemetry-bundle/blob/main/src/Instrumentation/Symfony/HttpKernel/TraceableHttpKernelEventSubscriber.php#L294

Here a little PHP code to reproduce the behavior:

```
<?php

$combinedExcludePaths = implode('|', []);
$result = preg_match("#{$combinedExcludePaths}#", '/foo');

var_dump($result); // 1
```

Is it made on purpose or is it a bug ?
