### ISSUE TITLE
Sampling - Dynamic ratio based on the incoming request

### ISSUE THREAD

**Issue by jvocampings** [FriendsOfOpenTelemetry/opentelemetry-bundle#169]
Hello

See below how I configured a trace provider with the behaviour "parent based"

```
providers:
    default:
        type: default
        sampler:
            type: parent_based_trace_id_ratio
            options:
                - 1 # ratio
        processors:
            - 'open_telemetry.traces.processors.simple'
```

The ratio is configurable but it is set for the whole application. I think we need a ratio based on the incoming request e.g.

```
providers:
    default:
        type: default
        sampler:
            type: parent_based_trace_id_ratio
            ratio_configuration:
                default:
                    ratio: 0.1
                ratio_by_endpoint:
                    - ratio: 1.0
                      endpoints:
                          - GET /foo
                          - GET /var
                    - ratio: 0.0001
                      endpoints:
                          - POST /foo
                    - ratio: 0.5
                      endpoints:
                          - PATCH /foo
```

Some endpoints in a same app could be very critical in term of execution time. The overhead added by Open Telemetry could leads to business issue.

Maybe we also need a ratio by Symfony Command and by message (Messenger). Not all commands and messages need the same ratio of sampling. e.g. for command/message with low volumetry and no need of great speed, we may need a ratio of 1.0. But for something executed millions of time, a ratio of 0.00001 may be enought.

What do you think of it ?

edit: in my proposal, I use a new property `ratio_configuration` to avoid bc break.

**Comment by jvocampings** [comment]
After looking the code, maybe there is other solutions.

- use a sampler of type `service` to configure a custom sampler which decorates a native sampler with a dynamic ratio
- override `open_telemetry.traces.sampler_factory`

**Comment by gaelreyrol** [comment]
Hi @jvocampings, 

I absolutely agree, managing the sampling from the configuration is not the best option! But as you noticed you can use a service sampler that extends the TraceIdRatioBasedSampler to give a specific probability based on its route.

One of my goals with this bundle is to provide a seamless integration, by making use of the `[#Trace]` attribute. It would provide a way to sample this closely to the routes, messages and everything that can be traced.

For example with a controller method:
```php
#[Traceable(ratio: 0.1)]
#[Route('/healthcheck', methods: ['GET'])]
public function healthcheck(): Response
{
    return $this->json([
        'status' => 'ok',
    ]);
}
```

I will create an issue to expose this, until then you can use a service to implement your own expectations.

Regards

**Comment by gaelreyrol** [comment]
I created the issue #170 to expose the feature I explained. Do you need help on implementing a sampler service or can I close this issue?

**Comment by jvocampings** [comment]
I think you can close the issue. I did something like that and it seems ok.

Bundle conf:
```
    traces:
        tracers:
            main:
                provider: 'open_telemetry.traces.providers.default'
        providers:
            default:
                type: default
                sampler:
                    type: service
                    service_id: 'App\OpenTelemetry\Trace\Sampler\DynamicParentBasedTraceIdRatio'
                processors:
                    - 'open_telemetry.traces.processors.simple'
```

App conf:
```
    App\OpenTelemetry\Trace\Sampler\DynamicParentBasedTraceIdRatio:
        class: App\OpenTelemetry\Trace\Sampler\DynamicParentBasedTraceIdRatio
        factory: ['@App\OpenTelemetry\Trace\Sampler\DynamicParentBasedTraceIdRatioFactory', 'create']
```

The custom sampler:
```
readonly class DynamicParentBasedTraceIdRatio implements SamplerInterface
{
    public function __construct(
        private ParentBased $sampler,
    ) {
    }

    public function shouldSample(ContextInterface $parentContext, string $traceId, string $spanName, int $spanKind, AttributesInterface $attributes, array $links): SamplingResult
    {
        return $this->sampler->shouldSample($parentContext, $traceId, $spanName, $spanKind, $attributes, $links);
    }

    public function getDescription(): string
    {
        return 'Dynamic+'.$this->sampler->getDescription();
    }
}
```
The factory:
```
public function create(): DynamicParentBasedTraceIdRatio
    {
        $ratio = 0.0001
        $request = $this->requestStack->getCurrentRequest();

        // analyze the request to resolve ratio
        //............

        return new DynamicParentBasedTraceIdRatio(
            new ParentBased(
                new TraceIdRatioBasedSampler($ratio)
            )
        );
    }
```
