### ISSUE TITLE
Auto-instrument Doctrine DBAL queries & ORM lifecycle events

### ISSUE THREAD

**Issue by gaelreyrol** [FriendsOfOpenTelemetry/opentelemetry-bundle#18]
Doctrine should be auto-instrumented through a middleware.

Documentation: https://www.doctrine-project.org/projects/doctrine-bundle/en/2.11/middlewares.html

## Configuration

```yaml
open_telemetry:
  instrumentation:
    doctrine:
      enabled: true
      tracing:
        enabled: true
        tracer: ~
      metering:
        enabled: true
        meter: ~
```

When `open_telemetry.instrumentation.doctrine.enabled` is set to false, a compiler pass should remove the tag `doctrine.middleware` from the middleware.

The value of `open_telemetry.instrumentation.doctrine.tracing.tracer`  should target the default tracer if not defined or not overwritten, if set it should match a tracer defined in `open_telemetry.traces.tracers`.

The value of `open_telemetry.instrumentation.doctrine.metering.meter` should target the default meter if not defined or not overwritten, if set it should match a meter defined in `open_telemetry.metrics.meters`.
