### ISSUE TITLE
Auto-instrument Symfony HttpKernel events

### ISSUE THREAD

**Issue by gaelreyrol** [FriendsOfOpenTelemetry/opentelemetry-bundle#2]
HttpKernel events should be auto-instrumented through an EventSubscriber.

Documentation: https://symfony.com/doc/current/reference/events.html

## Configuration

```yaml
open_telemetry:
  instrumentation:
    kernel:
      enabled: true
      tracing:
         enabled: true
         tracer: ~
      metering:
        enabled: true
        meter: ~
```

When `open_telemetry.instrumentation.kernel.enabled` is set to false, a compiler pass should remove the tag `kernel.event_subscriber` from the EventSubscriber.

The value of `open_telemetry.instrumentation.kernel.tracing.tracer` should target the default trace provider if not defined or not overwritten, if set it should match a provider defined in `open_telemetry.traces.tracers`.

The value of `open_telemetry.instrumentation.kernel.metering.meter` should target the default meter provider if not defined or not overwritten, if set it should match a provider defined in `open_telemetry.metrics.meters`.

### `KernelEvents::EXCEPTION`
