### ISSUE TITLE
Use service identifiers instead of raw keys in configuration

### ISSUE THREAD

**Issue by gaelreyrol** [FriendsOfOpenTelemetry/opentelemetry-bundle#29]
Currently to inject a provider on a service we use an array key prototype which does not rely on a service identifier.

Here is an example:
```yaml
open_telemetry:
  instrumentation:
    http_kernel:
      enabled: true
      tracer: main # raw key referencing open_telemetry.tracers.tracers.main
  traces:
    tracers:
      main:
        provider: default # raw key referencing open_telemetry.traces.providers.default
    providers:
      default:
        type: default
        sampler: always_on # raw key referencing open_telemetry.traces.samplers.always_on
        processors:
          - otlp # raw key referencing open_telemetry.traces.processors.default
    processors:
      otlp:
        type: simple # raw key referencing open_telemetry.traces.span_processors.simple - not implemented yet as service
        exporter: otlp # raw key referencing open_telemetry.traces.exporters.otlp
    exporters:
      otlp:
        dsn: http+otlp://localhost:4318
```
We should replace these raw keys with service ids:
```yaml
open_telemetry:
  instrumentation:
    http_kernel:
      enabled: true
      tracer: 'open_telemetry.tracers.tracers.main'
  traces:
    tracers:
      main:
        provider: 'open_telemetry.traces.providers.default'
    providers:
      default:
        type: default
        sampler: 'open_telemetry.traces.samplers.always_on' - not implemented yet as service
        processors:
          - 'open_telemetry.traces.processors.default"
    processors:
      otlp:
        type: 'open_telemetry.traces.span_processors.simple'
        exporter: 'open_telemetry.traces.exporter.otlp'
    exporters:
      otlp:
        dsn: http+otlp://localhost:4318
```
